from qcm_maker_screens.qcm_window import QCMWindow
from qcm_maker_screens.menu_window import MenuWindow
from qcm_maker_screens.database_window import DatabaseWindow
from qcm_maker_screens.classes_window import ClassesWindow
